[tools]
opentofu = "1.11.4"
awscli = "latest"
opencode = "1.2.10"
bun = "1.3.9"
terramate = "0.16.0"
buf = "latest"

[settings]
experimental = true

[tasks.format]
description = "Format all code"
alias = ["fmt"]
depends = ["format:*"]

[tasks."format:tofu"]
description = "Format OpenTofu code recursively"
alias = ["fmt:tofu"]
run = "tofu fmt -recursive"

[tasks."format:terramate"]
description = "Format Terramate files"
alias = ["fmt:terramate"]
run = "terramate fmt"
