[tools]
opentofu = "1.11.4"
awscli = "latest"
opencode = "1.2.10"
bun = "1.3.9"
terramate = "0.16.0"
buf = "latest"

[settings]
experimental = true

# Lint and Format

[tasks.format]
run = "tofu fmt -recursive"
