##@ Lint and Formatting

[tasks.format]
description = "Format all code"
alias = ["fmt"]
depends = ["format:*"]

[tasks."format:tofu"]
description = "Format OpenTofu code recursively"
alias = ["fmt:tofu"]
run = "tofu fmt -recursive"
